# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd5ad9508fd9bbcde7b03c2f45daab3d83a8856aed5348e573566da9c318dfc2f5895727c8c2bd69a596f54ab03df09a709d985c655533c269e1a277c095d803

test:
  secret_key_base: ab7b8a2cd06f8003b570f8506c6e71bdc493e724ab235021c8fe16a0953d520b4f2a53afadd9b31235dde40a4ae5bb68102d6310987d1847c0bbfcacb2b12642

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
